---
- name: PLaybook to install generic tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  vars:
   TFROM: 1.14.3
  tasks:
    - name: check the hostnames
      shell: cat /etc/lsb-release
    - name : perform update
      shell : apt-get update
    -  name : install unzip
       shell : apt-get install -y stress unzip net-tools
 